# Generated by Django 4.2.2 on 2024-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('customer', 'Customer')], default='customer', max_length=10),
            preserve_default=False,
        ),
    ]
