# Generated by Django 4.2.2 on 2024-02-13 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sunday_open', models.TimeField(blank=True, null=True)),
                ('Sunday_close', models.TimeField(blank=True, null=True)),
                ('Monday_open', models.TimeField(blank=True, null=True)),
                ('Monday_close', models.TimeField(blank=True, null=True)),
                ('Tuesday_open', models.TimeField(blank=True, null=True)),
                ('Tuesday_close', models.TimeField(blank=True, null=True)),
                ('Wednesday_open', models.TimeField(blank=True, null=True)),
                ('Wednesday_close', models.TimeField(blank=True, null=True)),
                ('Thursday_open', models.TimeField(blank=True, null=True)),
                ('Thursday_close', models.TimeField(blank=True, null=True)),
                ('Friday_open', models.TimeField(blank=True, null=True)),
                ('Friday_close', models.TimeField(blank=True, null=True)),
                ('Saturday_open', models.TimeField(blank=True, null=True)),
                ('Saturday_close', models.TimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
