# Generated by Django 4.2.2 on 2024-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_businesshours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='Friday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Friday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Monday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Monday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Saturday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Saturday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Sunday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Sunday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Thursday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Thursday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Tuesday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Tuesday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Wednesday_close',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='Wednesday_open',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
