# Generated by Django 4.2.2 on 2024-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
    ]
