# Generated by Django 4.2.2 on 2024-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_businesshours_close_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='close_time',
            new_name='friday_close_time',
        ),
        migrations.RenameField(
            model_name='businesshours',
            old_name='open_time',
            new_name='friday_open_time',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='day',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='monday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='monday_open_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='saturday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='saturday_open_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='sunday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='sunday_open_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='thursday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='thursday_open_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='tuesday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='tuesday_open_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='wednesday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='wednesday_open_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
