# Generated by Django 4.2.2 on 2024-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_rename_close_time_businesshours_friday_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='friday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='monday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='saturday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='sunday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='thursday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='tuesday_close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='wednesday_close_time',
            field=models.TimeField(default='17:00'),
        ),
    ]
