# Generated by Django 4.2.2 on 2024-03-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_remove_businesshours_owner_businesshours_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='users',
        ),
    ]
