# Generated by Django 4.2.2 on 2024-03-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
    ]
