# Generated by Django 4.2.2 on 2024-03-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_remove_appointment_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='owner',
        ),
    ]
