# Generated by Django 4.2.2 on 2024-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_reminderoption_userprofile_receive_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled')], default='scheduled', max_length=10),
        ),
    ]
