# Generated by Django 4.2.2 on 2024-03-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
