# Generated by Django 4.2.2 on 2024-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_options',
            field=models.ManyToManyField(blank=True, to='appointments.reminderoption'),
        ),
    ]
