# Generated by Django 4.2.2 on 2024-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_reminder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
