# Generated by Django 4.2.2 on 2024-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_remove_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
