# Generated by Django 4.2.2 on 2024-03-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_options',
            field=models.ManyToManyField(blank=True, to='appointments.reminderoption'),
        ),
    ]
