# Generated by Django 4.2.2 on 2024-03-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_reminderoption_userprofile_receive_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_options',
            field=models.ManyToManyField(blank=True, to='appointments.reminderoption'),
        ),
    ]
