# Generated by Django 4.2.2 on 2024-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0030_appointment_reminder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_options',
        ),
    ]
